version: '3.8'

services:
  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      -  ./:/home/node/app
    depends_on:
      - database

      # Uncomment the below line if you dome/joao/Documentoseveloping on MacOS
      #- /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
  database:
    image: mysql
    platform: linux/x86_64
    container_name: bootcamp_cataline
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'adonis'
    ports:
      - '3306:3307'
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - database
